config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :restaurants do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORY = %w[chinese italian japanese french belgian].freeze
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality:
  { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to @restaurant
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants</h1>
</div>

  <hr>
  <% @restaurants.each do |restaurant| %>
    <p>
      <div class="container"><%= link_to restaurant.name, restaurant_path(restaurant), class: 'text-decoration-none' %></div>
    </p>
  <% end %>

<div class="container"><%= link_to 'Add Restaurant', new_restaurant_path, class: 'btn btn-sm btn-success' %></div>

app/views/restaurants/new.html.erb
<div class="container">
  <h2>New Restaurant</h2>
</div>
<div class="container">
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category, collection: Restaurant::CATEGORY %>
    <%= f.input :phone_number %>
    <%= f.submit class: 'btn btn-sm btn-success' %>
  <% end %>
  <%= link_to 'back', restaurants_path, class: "btn btn-sm btn-primary my-3" %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h2><%= @restaurant.name %></h2>

  <p><strong>Address:</strong> <%= @restaurant.address%></p>
  <p><strong>Phone Number:</strong> <%= @restaurant.phone_number %></p>
  <p><strong>Category:</strong> <%= @restaurant.category %></p>
  <div class="contai"><h3>Reviews</h3></div>
  <% @restaurant.reviews.each do |review| %>
    <div class="list-group-item w-50 mb-3"><p><%= review.content %></p>
    <p><% review.rating.times do %> ⭐ <% end %>
    </p></div>
  <% end %>
  <%= link_to 'back', restaurants_path, class: "btn btn-sm btn-primary" %>
  <%= link_to 'Add Review', new_restaurant_review_path(@restaurant), class: "btn btn-sm btn-warning" %>
</div>

app/views/reviews/new.html.erb
<div class="container"><h2>Add Review</h2></div>

<div class="container">
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: (1..5) %>
    <%= f.submit class: 'btn btn-sm btn-success' %>
<% end %>